Quotes.js

Fixes #3 
added new quotes for life and inspiration

added new quotes

---

assets/css/style.css
index.html

Fixes #6 
new color schemes
@Shariar-Hasan please consider this i have made some color updates as u said

adding some styles and updates

---

Quotes.js

Success and Persistence quotes

Add new quotes

---

Quotes.js

Added 10 new quotes to the quotes.js file

[Added] Added 10 new quotes

---

Quotes.js

#1 
Hey!! I have added 10 New Quotes. I request you to accept my PR.

Added new quote

---

Contributors/contributors.html
Contributors/script.js
Contributors/styles.css
assets/css/style.css
index.html

https://github.com/Shariar-Hasan/QuoteVerse/assets/132741672/d3c9bef0-9ba4-4d2f-bda9-ce01405cb9e9

Added the Contributors page

---

Contributors/script.js
Contributors/styles.css

added hyperlinks on contributors to redirect to the respective profiles and updated the styling
closes #24

feat: contributors profile hyperlink

---

assets/css/style.css
index.html
source/partials/_variables.scss

feature : Button change
issue fix: #23

feat: Button change #23

---

assets/css/style.css
index.html

[FEATURE]:Added Whatsapp share button

---

Quotes.js

Adding Quotes

---

index.html

Added the facebook share button link

---

Quotes.js

#11 
I have added 10 new Quotes following the guidelines .
I request you to accept my PR.

Added 10 New Quotes

---

Contributors/contributors.html
Contributors/styles.css

feat: added a back button on the contributors page to go back to the quotes page
closes #32

feat: back button on contributors page

---

Quotes.js

feat: added 5 quotes about programming

Added 5 more qoutes

---

assets/css/style.css

behavior of the controller-group is fixed, for all display-sizes.

fix: fixed the controller-gruop div behaviour.

---

Quotes.js

In this pull request I have added 10 new quotes towards Hactoberfest open-source contest.

feat: Added 10 new quotes for Hactoberfest 

---

assets/css/style.css
assets/js/main.js
index.html

Fixes #50 
This PR will implement functionality to copy the quote into user's clipboard with maximum browser compatibility, I have read the contribution guideline and followed it but in case I missed anything let me know, and forgive me for choosing any wrong color because there is no style guide is there in the contribution guideline, but I will correct color codes if anyone not like it.
Thanks ,
Jenish

Feat: Copy to Clipboard

---

assets/css/style.css
assets/js/main.js

Fix #58 
This PR will implement smooth text lift-up animation on added by text container. This will improve user experience by making smooth animation effects.
https://github.com/Shariar-Hasan/QuoteVerse/assets/99007146/6a7ee3de-6b3d-451a-b11c-8730c4dd2719
Thanks,
Jenish

feat: Implementation of css animation for added by div

---

Quotes.js

feat: adding quotes of inspirational category

Added Quotes

---

assets/css/style.css
assets/js/main.js
assets/js/others.js

Added swift-up animation effect on quote text without using any third-party package or library.
Let me know if it looks to be merged.
Thanks,
Hassan

feat: Animation Effect on Quote

---

assets/js/main.js

My PR closes #63
I modified the code to select the text of the quote, previously it was selecting html.
Not a UI issue

fix: Copy to clipboard

---

Quotes.js

I made changes to Quote.js
I added 3 motivational quotes and 3 programming quotes

feat: adding 3 motivational, and 3 programming quotes

---

assets/css/style.css
index.html

**My PR closes #66 **
- set the height of the container to occupy full screen height
- increased font-size for small screens

Improve UI alignment for mobile devices

---

index.html

My PR closes #68 
I modified the code to select the text of the quote, previously it was selecting HTML to share it to Whatsapp. I also improved it to open a WhatsApp window in a new tab.
Replaced innerHTML to innerText to select text instead of html.
Added target as _blank to open Whatsapp in a new tab.
Please add the hacktoberfest-accepted label in this PR after it gets merged

fix: Whatsapp sharing bug fix and improvement

---

index.html

**My PR closes #13 **
-Added a share to twitter(X) button
-Fixed Whatsapp share button

[feat]: add twitter share button

---

Quotes.js

feat: add some quotes

---

Quotes.js

feat: Added 5 new quotes

---

index.html

**My PR closes #51**
made it so that the link becomes purple when the background blends with the link color
tried different ways llike chroma.js, colors.ja, but found this to work best

change link color with respect to background color

---

Quotes.js

feat: Add quotes of inspirational ,Programming, Life categories 

---

index.html

I added meta tags for website description while sharing

added meta tags

---

Quotes.js

feat: adding quotes of various category

---

Quotes.js

My PR closes #80  
feat: adding 1 motivational and 4 quotes of technology category

feat: adding 1 motivational and 4 quotes of technology category #80

---

assets/js/main.js

Arranging quotes categories by ascending order.
**My PR closes #88 ** 
Arrange Quotes Category Options in Alphabetical Order with 'Random' as a First Option for enhancing user experience.

feat: Arranging quotes categories by ascending order.

---

Quotes.js

Added few quotes to quotes.json.

Added few quotes.

---

Quotes.js

feat: adding quotes of life, motivational category

---

Quotes.js

educational
category
#What This PR Do
**My PR  Added quotes** 
I have come across some truly inspiring quotes in the educational category. After scouring various platforms, I have handpicked the top 5 that I believe will leave a lasting impact on you. I hope you find them as thought-provoking and insightful as I did.

feat: adding quotes of Educational  category

---

assets/css/style.css
index.html

Hover effect added

---

Quotes.js

Added 6 Quotes in Quotes.js file

feat: Added 6 Quotes

---

Quotes.js

I added 5 new quotes. 
{
quote: "The key to success is to keep growing in all areas of life",
category: "Gym",
author: "Brian Tracy",
addedBy: "yasarlabib",
},
{
quote: "The road to success is always under construction",
category: "Life",
author: "Lily Tomlin",
addedBy: "yasarlabib",
},
{
quote: "It's not about perfect It's about effort And when you bring that effort every single day, that's where transformation happens That's how change occurs",
category: "Life",
author: "Jen Widerstrom",
addedBy: "yasarlabib",
},
{
quote: "You are never too old to set another goal or to dream a new dream",
category: "Life",
author: "C.S. Lewis",
addedBy: "yasarlabib",
},
{
quote: "Successful people do what unsuccessful people are not willing to do Don't wish it were …

added 5 new quotes to Quotes.js

---

Quotes.js

feat: contribution Himanshi Rana

---

Quotes.js

Hello @Shariar-Hasan This repo is perfect for a beginner like me to get started with Hactoberfest. Thank you for creating this repo. Added a quote, please give your suggestions.

feat: Added new motivational quote

---

Quotes.js

Added some quotes under the Art category.

feat: Added quotes for art category

---

Quotes.js

Hey @Shariar-Hasan, I noticed that there is only 1 quote in the "Gym" Category so I have added more quotes for gym. Please provide your suggestions if any changes are needed. 
For this category generally The authors are not known So i couldn't find a lot of quotes. I'll add more when I find.

feat: added gym quotes

---

Quotes.js

Adding quotes of motivation, philosophy, inspiration and love category.

Feat : Adding quotes of motivation, philosophy, inspiration and love category

---

Quotes.js

**My PR closes ** 
Added Quotes of Learning and Education category. Its my first proper contribution so please guide if there anything wrong.

feat: Adding quotes of Learning and Education category

---

Quotes.js

-  Added 5 Quotes in various categories.

added 5 quotes

---

Quotes.js

feat: adding quotes of educational category

---

Quotes.js

**My PR closes https://github.com/Shariar-Hasan/QuoteVerse/issues/146
Added Quotes 
hey @Shariar-Hasan 
I have added the quotes please review the PR

Added Quotes, HacktoberFest 2K23'

---

Quotes.js

Ref https://github.com/Shariar-Hasan/QuoteVerse/issues/93

feat: Added some quotes by Rabindranath Tagore and Lala Lajpat Rai

---

Quotes.js

feat: adding quotes for Life category

Added 5 New Quote

---

Duplicates.txt
Quotes.js

**My PR closes https://github.com/Shariar-Hasan/QuoteVerse/issues/150#event-10779105904
Hey @Shariar-Hasan 
I have successfully removed the duplicates quotes which are present in the data base
Please review it

Duplicates Removed

---

Quotes.js

feat: Adding 13 Philosophy Quotes

---

Quotes.js

Added 5 Quotes in Quotes.js based on motivation and philosophy.

feat: adding quotes of motivational and philosophical category

---

Quotes.js

**My PR closes #issue_number_here**

feat: adding quotes of life category

---

Quotes.js

Added some new motivational quotes

---

Quotes.js

I've added new quotes to the QuoteVerse project. These quotes mainly cover Motivational category. Each quote follows the specified format with the author and category.
NA

Adding 5 motivational quotes

---

Quotes.js

Added 10 Quotes in Quotes.js under multiple categories.

feat: adding quotes of mixed categories

---

Quotes.js

I have added cool environment and nature related Quotes in this website.
Around 15 cool quotes have been added related to environment.

quotes related to environment has been added

---

.gitignore
.prettierrc
Quotes.js
package-lock.json
package.json

**My PR closes #160 
I added prettier as one of the npm dependencies so any editor using prettier as code formatter will work based on the local file.
This will keep the code more maintainable for the authors and other contributors because adding quotes for a PR shouldn't mean you have to format the entire file according to your configuration.
I am attaching a screenshot of sample formatting in Quote.js file so you can view it.
If its not an UI issue, then type "Not an UI issue" -->

[BUG] : Added .prettier config

---

Quotes.js

Added 7 Quotes in Quotes.js in Friendship Category.

Feat: Added Quote for Friendship Category

---

Quotes.js

feat: Added 47 historical quotes

---

Quotes.js

Added new 7 Happiness Category Quotes

feat: Added Quote for Happiness Category

---

Contributors/contributors.html

**My PR closes #168** 
Added the logo onto the tab section of the Contributors Page

Added the logo to Contributors Page

---

Duplicates.txt
Quotes.js

add feat: 5 quotes of different author

---

Quotes.js

feat: Adding 93 Happiness Category quotes

---

Contributors/styles.css
assets/css/style.css
assets/js/main.js
index.html

My PR closes  #151 
I reduced the border width and added the colour picker using the colour picker class and added the adjusting brightness function which calculates if the brightness is low on the theme or high and according to it, it changes the text colour to black and white. Also, I changed the Contributors page according to the home page of the quotation.
The approach of these changes is to make the user feel at ease and focused on the things he needs to achieve. Changing the UI to a more simple one allows the user to feel more simple. Allowing the different colours approach for the quotations background gives the user flexibility to choose their own favourite background colour.
On the other hand, the Contributors page only changes the UI to match the previous Home page.
It might …

UI Changes

---

Quotes.js
package-lock.json

I have added 5 unique Education Quotes added in the last of the Quotes.js file all according to instructions provided by you in Contributing.md file.
Not an UI issue.

feat: 5 Education Quotes added

---

assets/css/style.css
assets/js/main.js
index.html
package-lock.json
package.json

**My PR closes #183** 
* Implemented the Like functionality for quotes.
* Users can now click on a heart icon to like a quote. The like status is saved to localStorage and persists across page refreshes.
* If a quote is liked, the heart icon will remain active, and unliked quotes will not store in localStorage by default.
* Handled cases where quotes are unliked, ensuring proper toggle of the heart icon and clearing the quote from localStorage if unliked.

Add Like Functionality

---

assets/css/style.css

Generate & Tab ,margin added

---

assets/css/style.css

Changed spacing

---

Quotes.js

Fix/ Crush Issue at UI

---

Quotes.js

* I fixed Quotes.js (some commas were missing);
* I added 10 quotes.

fix: Quotes.js + feat: add 10 quotes
